#!/usr/bin/env python3
import argparse
import os
import re
import json

def update_monitor_config(file_path, monitor_name, res="preferred", pos="auto", scale="1", transform=None, vrr=None, mirror=None, disabled=False, is_primary=False):
    if not os.path.exists(file_path):
        with open(file_path, 'w') as f:
            f.write("# Hyprland Monitor Configuration\n")

    with open(file_path, 'r') as f:
        lines = f.readlines()

    original_content_lines = []
    pattern = re.compile(rf'^\s*monitor\s*=\s*{re.escape(monitor_name)}\s*,', re.IGNORECASE)
    
    for line in lines:
        if pattern.match(line):
            continue 
        original_content_lines.append(line)

    if disabled:
        monitor_line = f"monitor = {monitor_name}, disable\n"
    else:
        line_parts = [f"{monitor_name}", f"{res}", f"{pos}", f"{scale}"]
        if transform is not None: line_parts.append(f"transform,{transform}")
        if vrr is not None: line_parts.append(f"vrr,{vrr}")
        if mirror: line_parts.append(f"mirror,{mirror}")
        monitor_line = f"monitor = {', '.join(line_parts)}\n"

    if is_primary:
        new_lines = [monitor_line] + original_content_lines
    else:
        new_lines = original_content_lines + [monitor_line]

    with open(file_path, 'w') as f:
        f.writelines(new_lines)

def save_all_monitors(file_path, monitors_json):
    try:
        monitors = json.loads(monitors_json)
    except Exception as e:
        print(f"Error parsing JSON: {e}")
        return

    lines = ["# Hyprland Monitor Configuration\n", "# Generated by Quickshell SystemDisplay\n"]
    for m in monitors:
        name = m.get("name")
        if not name: continue
        res = m.get("res", "preferred")
        pos = m.get("pos", "auto")
        scale = m.get("scale", "1")
        transform = m.get("transform")
        vrr = m.get("vrr")
        mirror = m.get("mirror")
        disabled = m.get("disabled", False)

        if disabled:
            lines.append(f"monitor = {name}, disable\n")
        else:
            parts = [f"{name}", f"{res}", f"{pos}", f"{scale}"]
            if transform is not None: parts.append(f"transform,{transform}")
            if vrr is not None: parts.append(f"vrr,{vrr}")
            if mirror: parts.append(f"mirror,{mirror}")
            lines.append(f"monitor = {', '.join(parts)}\n")

    with open(file_path, 'w') as f:
        f.writelines(lines)
    print(f"Bulk updated {len(monitors)} monitors in {file_path}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Update Hyprland monitor configuration.")
    parser.add_argument("--file", default="~/.config/hypr/monitors.conf", help="Path to monitors.conf")
    parser.add_argument("--name", help="Monitor name (e.g., eDP-1)")
    parser.add_argument("--res", default="preferred", help="Resolution@Refresh")
    parser.add_argument("--pos", default="auto", help="Position")
    parser.add_argument("--scale", default="1", help="Scaling factor")
    parser.add_argument("--transform", type=int, help="Rotation")
    parser.add_argument("--vrr", type=int, help="VRR")
    parser.add_argument("--mirror", help="Monitor name to mirror")
    parser.add_argument("--primary", action="store_true", help="Set as primary")
    parser.add_argument("--disable", action="store_true", help="Disable monitor")
    parser.add_argument("--all", help="JSON string representing all monitors for bulk update")
    
    args = parser.parse_args()
    file_path = os.path.expanduser(args.file)
    
    if args.all:
        save_all_monitors(file_path, args.all)
    elif args.name:
        update_monitor_config(file_path, args.name, res=args.res, pos=args.pos, scale=args.scale, 
                            transform=args.transform, vrr=args.vrr, mirror=args.mirror, 
                            disabled=args.disable, is_primary=args.primary)
    else:
        parser.print_help()
