[config]
version_check = false

[templates.m3colors]
input_path = '~/.config/matugen/templates/colors.json'
output_path = '~/.local/state/quickshell/user/generated/colors.json'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland/colors.conf'
output_path = '~/.config/hypr/hyprland/colors.conf'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprland/hyprlock-colors.conf'
output_path = '~/.config/hypr/hyprlock/colors.conf'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel/fuzzel_theme.ini'
output_path = '~/.config/fuzzel/fuzzel_theme.ini'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-3.0/gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-4.0/gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.kde_colors]
input_path = '~/.config/matugen/templates/kde/color.txt'
output_path = '~/.local/state/quickshell/user/generated/color.txt'

[templates.wallpaper]
input_path = '~/.config/matugen/templates/wallpaper.txt'
output_path = '~/.local/state/quickshell/user/generated/wallpaper/path.txt'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'

[templates.heroic]
input_path = '~/.config/matugen/templates/heroic.css'
output_path = '~/.config/heroic/matugen.css'

[templates.micro]
input_path = '~/.config/matugen/templates/micro.micro'
output_path = '~/.config/micro/colorschemes/matugen.micro'

[templates.equibop]
input_path = '~/.config/matugen/templates/midnight-discord.css'
output_path = '~/.config/equibop/themes/midnight-discord.css'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.millennium]
input_path = '~/.config/matugen/templates/matugentemplate.css'
output_path = '~/.steam/steam/steamui/skins/Material-Theme/css/main/colors/matugen.css'

[templates.iisddmtheme]
input_path = '~/.config/ii-sddm-theme/SddmColors.qml'
output_path = '~/.config/ii-sddm-theme/Colors.qml'
post_hook = 'python3 ~/.config/ii-sddm-theme/generate_settings.py && sudo ~/.config/ii-sddm-theme/sddm-theme-apply.sh &'

